FROM centos:latest

MAINTAINER matthijs@magnetic.io

ADD https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar /opt/sbt-launch.jar

RUN yum -y update && \
    yum -y install java-1.8.0-openjdk git rpmdevtools

WORKDIR /project

ENTRYPOINT ["java", "-Xms512M", "-Xmx1536M", "-Xss1M", "-XX:+CMSClassUnloadingEnabled", "-Dsbt.global.base=/sbt/0.13", "-Dsbt.ivy.home=/ivy2", "-Dsbt.boot.directory=/sbt/boot", "-jar", "/opt/sbt-launch.jar"]


