require_relative '.vagrant/key_authorization'

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/jessie64'
  authorize_key_for_root config, '~/.ssh/id_dsa.pub', '~/.ssh/id_rsa.pub'
  {
    'build'    => '192.168.35.20' #,
#    'app1'        => '192.168.35.11'
  }.each do |short_name, ip|
    config.vm.define short_name do |host|
      host.vm.network 'private_network', ip: ip
      host.vm.hostname = "#{short_name}.vamp.dev"
    end
  end
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.cpus = 2
     vb.memory = "1024"
  end

end
