- name: Add SBT repo
  apt_repository: repo='deb http://dl.bintray.com/sbt/debian /' state=present


- name: Add backports, to install docker.io
  apt_repository: repo='deb http://http.debian.net/debian jessie-backports main'  state=present


- name: Update the cache
  apt: update_cache=yes


- name: Install utilities
  apt: name={{ item }} state=present update_cache=no
  with_items:
    - fakeroot
    - git
    - docker.io


- name: Install sbt
  apt: name={{ item }} state=present update_cache=no force=yes
  with_items:
    - sbt


- name: Set the locale
  locale_gen: name=en_GB.UTF-8 state=present


- name: Ensure github.com is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"